name: Build on Linux (only Wayland)

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: write

jobs:
  build-linux-wayland:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          repository: "joelvaz0x01/solar-system-opengl"
          submodules: true

      - name: Update repositories
        run: sudo apt update

      - name: Install OpenGL libraries
        run: sudo apt install libegl1-mesa-dev

      - name: Install Wayland libraries
        run: sudo apt install libwayland-dev libwayland-cursor0 libwayland-egl1-mesa libxkbcommon-dev

      - name: Set reusable strings
        id: strings
        shell: bash
        run: |
          echo "build-output-dir=${{ github.workspace }}/build-wayland" >> "$GITHUB_OUTPUT"
          PROJECT_VERSION=$(grep -E "^project\(solar_system VERSION" CMakeLists.txt | sed -E 's/.*VERSION ([0-9.]+).*/\1/')
          echo "project-version=$PROJECT_VERSION" >> "$GITHUB_OUTPUT"

      - name: Configure CMake for Wayland
        run: >
          cmake -B ${{ steps.strings.outputs.build-output-dir }}
          -DCMAKE_CXX_COMPILER=g++
          -DCMAKE_C_COMPILER=gcc
          -DCMAKE_BUILD_TYPE=Release
          -DGLFW_BUILD_WAYLAND=ON
          -DGLFW_BUILD_X11=OFF
          -S ${{ github.workspace }}

      - name: Build
        run: cmake --build ${{ steps.strings.outputs.build-output-dir }} --config Release
