name: CMake Linux X11 Build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: write

jobs:
  build-linux-x11:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        build_type: [Release, Debug]

    steps:
      - uses: actions/checkout@v4
        with:
          repository: "joelvaz0x01/solar-system-opengl"
          submodules: true

      - name: Update repositories
        run: sudo apt update

      - name: Install OpenGL libraries
        run: sudo apt install libegl1-mesa-dev

      - name: Install X11 libraries
        run: sudo apt install libxrandr-dev libx11-dev libxext-dev libxinerama-dev libxcursor-dev libxi-dev

      - name: Set reusable strings
        id: strings
        shell: bash
        run: |
          echo "build-output-dir=${{ github.workspace }}/build-x11" >> "$GITHUB_OUTPUT"
          PROJECT_VERSION=$(grep -E "^project\(solar_system VERSION" CMakeLists.txt | sed -E 's/.*VERSION ([0-9.]+).*/\1/')
          echo "project-version=$PROJECT_VERSION" >> "$GITHUB_OUTPUT"

      - name: Configure CMake for X11
        run: >
          cmake -B ${{ steps.strings.outputs.build-output-dir }}
          -DCMAKE_CXX_COMPILER=g++
          -DCMAKE_C_COMPILER=gcc
          -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
          -DGLFW_BUILD_WAYLAND=OFF
          -DGLFW_BUILD_X11=ON
          -S ${{ github.workspace }}

      - name: Build
        run: cmake --build ${{ steps.strings.outputs.build-output-dir }} --config ${{ matrix.build_type }}

      - name: Prepare artifacts
        run: |
          mkdir -p artifact-package
          cp bin/solar_system.out artifact-package/solar_system
          cp -r resources artifact-package/
          cp -r src/shaders artifact-package/
          cd artifact-package
          zip -r ../solar-system-linux-x11-${{ matrix.build_type }}.zip .

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v2
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        with:
          tag_name: v${{ steps.strings.outputs.project-version }}
          name: Solar System v${{ steps.strings.outputs.project-version }}
          draft: false
          prerelease: false
          files: solar-system-linux-x11-${{ matrix.build_type }}.zip
