name: CMake Windows Build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: write

jobs:
  build-windows:
    runs-on: windows-latest

    strategy:
      fail-fast: false
      matrix:
        build_type: [Release, Debug]

    steps:
      - uses: actions/checkout@v4
        with:
          repository: "joelvaz0x01/solar-system-opengl"
          submodules: true

      - name: Set reusable strings
        id: strings
        shell: pwsh
        run: |
          echo "build-output-dir=${{ github.workspace }}/build" >> "$env:GITHUB_OUTPUT"
          $PROJECT_VERSION = (Select-String -Path "CMakeLists.txt" -Pattern "^project\(solar_system VERSION" | ForEach-Object { $_.Line -replace '.*VERSION ([0-9.]+).*', '$1' })
          echo "project-version=$PROJECT_VERSION" >> "$env:GITHUB_OUTPUT"

      - name: Configure CMake
        run: >
          cmake -B ${{ steps.strings.outputs.build-output-dir }}
          -DCMAKE_CXX_COMPILER=cl
          -DCMAKE_C_COMPILER=cl
          -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
          -S ${{ github.workspace }}

      - name: Build
        run: cmake --build ${{ steps.strings.outputs.build-output-dir }} --config ${{ matrix.build_type }}

      - name: Prepare artifacts
        shell: bash
        run: |
          mkdir -p artifact-package
          cp bin/${{ matrix.build_type }}/solar_system.out.exe artifact-package/solar_system.exe
          cp -r resources artifact-package/
          cp -r src/shaders artifact-package/
          cd artifact-package
          7z a ../solar-system-windows-${{ matrix.build_type }}.zip .

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v2
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        with:
          tag_name: v${{ steps.strings.outputs.project-version }}
          name: Solar System v${{ steps.strings.outputs.project-version }}
          draft: false
          prerelease: false
          files: solar-system-windows-${{ matrix.build_type }}.zip
